/// <reference types="nativewind/types" />

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.

// Allow the side-effect `import './global.css'` in src/app/App.tsx to typecheck.
declare module '*.css';
