import {
  getMovementAppointment,
  getMovementOriginKey,
  getSignedQuantity,
  getSignedTotal,
  getUnitPluralForm,
  sortMovementsByDate,
  type StockMovement,
} from './stockMovement';

function movement(overrides: Partial<StockMovement> = {}): StockMovement {
  return {
    id: 'movement-1',
    itemName: 'Propofol 10mg/ml 20ml',
    unit: 'ampoule',
    type: 'outbound',
    source: 'appointment',
    quantity: 2,
    unitCost: 19.9,
    occurredAt: '2026-08-12T09:30:00',
    ...overrides,
  };
}

describe('getMovementOriginKey', () => {
  it.each([
    ['manualPurchase', 'manualPurchase'],
    ['orderImport', 'orderImport'],
    ['appointment', 'appointment'],
    ['correctionReversal', 'correctionReversal'],
  ] as const)('source "%s" maps to origin "%s"', (source, expected) => {
    expect(getMovementOriginKey(movement({ source }))).toBe(expected);
  });

  it.each([
    ['loss', 'adjustmentLoss'],
    ['expiration', 'adjustmentExpiration'],
    ['breakage', 'adjustmentBreakage'],
    ['other', 'adjustmentOther'],
  ] as const)(
    'manual adjustment with reason "%s" maps to origin "%s"',
    (adjustmentReason, expected) => {
      const result = getMovementOriginKey(
        movement({ source: 'manualAdjustment', adjustmentReason }),
      );

      expect(result).toBe(expected);
    },
  );

  it('falls back to "adjustmentOther" when an adjustment has no reason', () => {
    const result = getMovementOriginKey(
      movement({ source: 'manualAdjustment', adjustmentReason: undefined }),
    );

    expect(result).toBe('adjustmentOther');
  });
});

describe('getSignedQuantity', () => {
  it('keeps an inbound quantity positive', () => {
    expect(getSignedQuantity(movement({ type: 'inbound', quantity: 8 }))).toBe(
      8,
    );
  });

  it('turns an outbound quantity negative', () => {
    expect(getSignedQuantity(movement({ type: 'outbound', quantity: 8 }))).toBe(
      -8,
    );
  });

  it('reads the direction from the type, not from the stored sign', () => {
    expect(
      getSignedQuantity(movement({ type: 'outbound', quantity: 2.5 })),
    ).toBe(-2.5);
  });
});

describe('getSignedTotal', () => {
  it('values the quantity at the unit cost recorded with the movement', () => {
    const result = getSignedTotal(
      movement({ type: 'inbound', quantity: 5, unitCost: 189 }),
    );

    expect(result).toBe(945);
  });

  it('is negative for a saída, like the quantity', () => {
    const result = getSignedTotal(
      movement({ type: 'outbound', quantity: 2, unitCost: 19.9 }),
    );

    expect(result).toBeCloseTo(-39.8, 2);
  });

  it('values a fractional quantity', () => {
    const result = getSignedTotal(
      movement({ type: 'outbound', quantity: 1.5, unitCost: 34 }),
    );

    expect(result).toBe(-51);
  });

  it('is zero when the movement has no cost recorded', () => {
    const result = getSignedTotal(
      movement({ type: 'outbound', quantity: 3, unitCost: 0 }),
    );

    expect(result).toBe(-0);
  });
});

describe('getUnitPluralForm', () => {
  it('is singular for exactly one unit', () => {
    expect(getUnitPluralForm(movement({ quantity: 1 }))).toBe('one');
  });

  it.each([0, 2, 1.5, 0.5])('is plural for %s units', quantity => {
    expect(getUnitPluralForm(movement({ quantity }))).toBe('other');
  });
});

describe('getMovementAppointment', () => {
  const appointment = { id: 'appointment-1', label: 'Orquiectomia — Mel' };

  it('returns the appointment of a movement generated by an appointment', () => {
    const result = getMovementAppointment(
      movement({ source: 'appointment', appointment }),
    );

    expect(result).toEqual(appointment);
  });

  it('returns null when an appointment movement has no link stored', () => {
    const result = getMovementAppointment(
      movement({ source: 'appointment', appointment: undefined }),
    );

    expect(result).toBeNull();
  });

  it('ignores an appointment attached to a movement from another source', () => {
    const result = getMovementAppointment(
      movement({ source: 'manualPurchase', appointment }),
    );

    expect(result).toBeNull();
  });
});

describe('sortMovementsByDate', () => {
  it('orders movements from the most to the least recent', () => {
    const older = movement({ id: 'a', occurredAt: '2026-08-01T10:00:00' });
    const newer = movement({ id: 'b', occurredAt: '2026-09-01T10:00:00' });
    const middle = movement({ id: 'c', occurredAt: '2026-08-20T10:00:00' });

    const result = sortMovementsByDate([older, newer, middle]);

    expect(result.map(item => item.id)).toEqual(['b', 'c', 'a']);
  });

  it('breaks ties by id so the order is stable', () => {
    const first = movement({ id: 'b', occurredAt: '2026-08-01T10:00:00' });
    const second = movement({ id: 'a', occurredAt: '2026-08-01T10:00:00' });

    expect(sortMovementsByDate([first, second]).map(item => item.id)).toEqual([
      'a',
      'b',
    ]);
  });

  it('does not mutate the received list', () => {
    const movements = [
      movement({ id: 'a', occurredAt: '2026-08-01T10:00:00' }),
      movement({ id: 'b', occurredAt: '2026-09-01T10:00:00' }),
    ];

    sortMovementsByDate(movements);

    expect(movements.map(item => item.id)).toEqual(['a', 'b']);
  });

  it('returns an empty list unchanged', () => {
    expect(sortMovementsByDate([])).toEqual([]);
  });
});
